### ISSUE TITLE
Question about ImageNet dataset

### ISSUE THREAD

**Issue by marianpetruk** [facebookresearch/AttentiveNAS#1]
Could you please clarify the exact ImageNet Dataset you have used for training and testing? 
Is it the original ILSVRC2012 from https://image-net.org/challenges/LSVRC/2012/2012-downloads.php or from somewhere else?
Is it train and validation split or you have used test split as well? What was the number of images in train and validation dataset?

Also have you made any preprocessing, e.g. resizing or you took the raw images?

**Comment by dilinwang820** [comment]
Thank you for your interest. 
The ImageNet dataset used in this work refers to the "ILSVRC2012" ImageNet dataset, which has 1,281,116 training images and 50,000 validation images. We use the dataset as it is, we did not make any preprocessing after downloading. 
The results in table 1 are the accuracy on the validation dataset.
