### ISSUE TITLE
usage of function zero_residual_block_bn_weights

### ISSUE THREAD

**Issue by wmkai** [facebookresearch/AttentiveNAS#9]
Hi! Thanks for your great job! I want to know why the function `zero_residual_block_bn_weights` should be used? what will be happen if it is not used?

**Comment by dilinwang820** [comment]
We followed this setting suggested in the BigNAS paper - https://arxiv.org/pdf/2003.11142.pdf (first paragraph, page 6.)

**Comment by wmkai** [comment]
Thanks for your reply, it helps me a lot!
